// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcserver.proto

/*
Package rpcserver is a generated protocol buffer package.

It is generated from these files:
	rpcserver.proto

It has these top-level messages:
	String
	User
	StringRequest
	ServerQuery
	ServerReply
*/
package rpcserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type String struct {
	Str string `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
}

func (m *String) Reset()                    { *m = String{} }
func (m *String) String() string            { return proto.CompactTextString(m) }
func (*String) ProtoMessage()               {}
func (*String) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *String) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type User struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type StringRequest struct {
	Str       string `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	AuthToken string `protobuf:"bytes,2,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
}

func (m *StringRequest) Reset()                    { *m = StringRequest{} }
func (m *StringRequest) String() string            { return proto.CompactTextString(m) }
func (*StringRequest) ProtoMessage()               {}
func (*StringRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StringRequest) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *StringRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type ServerQuery struct {
	MessageId   int64  `protobuf:"varint,1,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	GetRam      bool   `protobuf:"varint,2,opt,name=get_ram,json=getRam" json:"get_ram,omitempty"`
	GetCpu      bool   `protobuf:"varint,3,opt,name=get_cpu,json=getCpu" json:"get_cpu,omitempty"`
	Command     string `protobuf:"bytes,4,opt,name=command" json:"command,omitempty"`
	ProcessName string `protobuf:"bytes,5,opt,name=process_name,json=processName" json:"process_name,omitempty"`
	AuthToken   string `protobuf:"bytes,6,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
}

func (m *ServerQuery) Reset()                    { *m = ServerQuery{} }
func (m *ServerQuery) String() string            { return proto.CompactTextString(m) }
func (*ServerQuery) ProtoMessage()               {}
func (*ServerQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServerQuery) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *ServerQuery) GetGetRam() bool {
	if m != nil {
		return m.GetRam
	}
	return false
}

func (m *ServerQuery) GetGetCpu() bool {
	if m != nil {
		return m.GetCpu
	}
	return false
}

func (m *ServerQuery) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ServerQuery) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *ServerQuery) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type ServerReply struct {
	Messages  []string `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	MessageId uint64   `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	RamUsage  string   `protobuf:"bytes,3,opt,name=ram_usage,json=ramUsage" json:"ram_usage,omitempty"`
	CpuUsage  string   `protobuf:"bytes,4,opt,name=cpu_usage,json=cpuUsage" json:"cpu_usage,omitempty"`
}

func (m *ServerReply) Reset()                    { *m = ServerReply{} }
func (m *ServerReply) String() string            { return proto.CompactTextString(m) }
func (*ServerReply) ProtoMessage()               {}
func (*ServerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServerReply) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *ServerReply) GetMessageId() uint64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *ServerReply) GetRamUsage() string {
	if m != nil {
		return m.RamUsage
	}
	return ""
}

func (m *ServerReply) GetCpuUsage() string {
	if m != nil {
		return m.CpuUsage
	}
	return ""
}

func init() {
	proto.RegisterType((*String)(nil), "String")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*StringRequest)(nil), "StringRequest")
	proto.RegisterType((*ServerQuery)(nil), "ServerQuery")
	proto.RegisterType((*ServerReply)(nil), "ServerReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPCServer service

type RPCServerClient interface {
	Version(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error)
	List(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error)
	Stop(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error)
	Start(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error)
	Kill(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error)
	InstanceStop(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error)
	Attach(ctx context.Context, in *ServerQuery, opts ...grpc.CallOption) (*ServerReply, error)
	Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*String, error)
}

type rPCServerClient struct {
	cc *grpc.ClientConn
}

func NewRPCServerClient(cc *grpc.ClientConn) RPCServerClient {
	return &rPCServerClient{cc}
}

func (c *rPCServerClient) Version(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/RPCServer/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServerClient) List(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/RPCServer/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServerClient) Stop(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/RPCServer/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServerClient) Start(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/RPCServer/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServerClient) Kill(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/RPCServer/Kill", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServerClient) InstanceStop(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/RPCServer/InstanceStop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServerClient) Attach(ctx context.Context, in *ServerQuery, opts ...grpc.CallOption) (*ServerReply, error) {
	out := new(ServerReply)
	err := grpc.Invoke(ctx, "/RPCServer/Attach", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServerClient) Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := grpc.Invoke(ctx, "/RPCServer/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPCServer service

type RPCServerServer interface {
	Version(context.Context, *StringRequest) (*String, error)
	List(context.Context, *StringRequest) (*String, error)
	Stop(context.Context, *StringRequest) (*String, error)
	Start(context.Context, *StringRequest) (*String, error)
	Kill(context.Context, *StringRequest) (*String, error)
	InstanceStop(context.Context, *StringRequest) (*String, error)
	Attach(context.Context, *ServerQuery) (*ServerReply, error)
	Auth(context.Context, *User) (*String, error)
}

func RegisterRPCServerServer(s *grpc.Server, srv RPCServerServer) {
	s.RegisterService(&_RPCServer_serviceDesc, srv)
}

func _RPCServer_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).Version(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCServer_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).List(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCServer_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).Stop(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCServer_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).Start(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCServer_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).Kill(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCServer_InstanceStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).InstanceStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/InstanceStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).InstanceStop(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCServer_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/Attach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).Attach(ctx, req.(*ServerQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCServer_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServerServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCServer/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServerServer).Auth(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RPCServer",
	HandlerType: (*RPCServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _RPCServer_Version_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RPCServer_List_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _RPCServer_Stop_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _RPCServer_Start_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _RPCServer_Kill_Handler,
		},
		{
			MethodName: "InstanceStop",
			Handler:    _RPCServer_InstanceStop_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _RPCServer_Attach_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _RPCServer_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcserver.proto",
}

func init() { proto.RegisterFile("rpcserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcb, 0x6e, 0xd4, 0x30,
	0x14, 0xd5, 0x74, 0x32, 0x79, 0xdc, 0x0e, 0x0f, 0x79, 0x01, 0x51, 0x10, 0x62, 0x88, 0x90, 0x60,
	0x95, 0x05, 0x48, 0xac, 0xa9, 0xba, 0xaa, 0x40, 0x08, 0x1c, 0xca, 0x36, 0x32, 0xce, 0x55, 0x26,
	0x62, 0x1c, 0x1b, 0x3f, 0x40, 0xdd, 0xf2, 0x1b, 0xfc, 0x09, 0x5f, 0x87, 0xec, 0x3c, 0xd4, 0x16,
	0x75, 0x76, 0x3e, 0xe7, 0xdc, 0x1c, 0x9f, 0xe3, 0x5c, 0x78, 0xa0, 0x15, 0x37, 0xa8, 0x7f, 0xa2,
	0xae, 0x94, 0x96, 0x56, 0x96, 0x05, 0xc4, 0xb5, 0xd5, 0xfd, 0xd0, 0x91, 0x87, 0xb0, 0x36, 0x56,
	0xe7, 0xab, 0xdd, 0xea, 0x55, 0x46, 0xfd, 0xb1, 0x7c, 0x0b, 0xd1, 0xa5, 0x41, 0x4d, 0x08, 0x44,
	0x03, 0x13, 0x38, 0x49, 0xe1, 0x4c, 0x0a, 0x48, 0x15, 0x33, 0xe6, 0x97, 0xd4, 0x6d, 0x7e, 0x12,
	0xf8, 0x05, 0x97, 0xef, 0xe0, 0xde, 0xe8, 0x49, 0xf1, 0x87, 0x43, 0x63, 0xff, 0xb7, 0x26, 0x4f,
	0x01, 0x98, 0xb3, 0xfb, 0xc6, 0xca, 0xef, 0x38, 0x4c, 0x06, 0x99, 0x67, 0xbe, 0x78, 0xa2, 0xfc,
	0xbb, 0x82, 0xd3, 0x3a, 0xc4, 0xfc, 0xec, 0x50, 0x5f, 0xf9, 0x71, 0x81, 0xc6, 0xb0, 0x0e, 0x9b,
	0xbe, 0x0d, 0x3e, 0x6b, 0x9a, 0x4d, 0xcc, 0x45, 0x4b, 0x1e, 0x43, 0xd2, 0xa1, 0x6d, 0x34, 0x13,
	0xc1, 0x2a, 0xa5, 0x71, 0x87, 0x96, 0x32, 0x31, 0x0b, 0x5c, 0xb9, 0x7c, 0xbd, 0x08, 0xe7, 0xca,
	0x91, 0x1c, 0x12, 0x2e, 0x85, 0x60, 0x43, 0x9b, 0x47, 0xe1, 0xf2, 0x19, 0x92, 0xe7, 0xb0, 0x55,
	0x5a, 0x72, 0x34, 0xa6, 0x09, 0xa5, 0x37, 0x41, 0x3e, 0x9d, 0xb8, 0x8f, 0xbe, 0xfb, 0xcd, 0xf0,
	0xf1, 0xed, 0xf0, 0xbf, 0x97, 0xf0, 0x14, 0xd5, 0xe1, 0xca, 0x3f, 0xd5, 0x14, 0xd5, 0xe4, 0xab,
	0xdd, 0xda, 0x3f, 0xd5, 0x8c, 0x6f, 0x15, 0xf3, 0xe1, 0xa3, 0xeb, 0xc5, 0x9e, 0x40, 0xa6, 0x99,
	0x68, 0x9c, 0x87, 0xa1, 0x41, 0x46, 0x53, 0xcd, 0xc4, 0xa5, 0xc7, 0x5e, 0xe4, 0xca, 0x4d, 0xe2,
	0xd8, 0x22, 0xe5, 0xca, 0x05, 0xf1, 0xf5, 0x9f, 0x13, 0xc8, 0xe8, 0xa7, 0xf3, 0x31, 0x07, 0x29,
	0x21, 0xf9, 0x8a, 0xda, 0xf4, 0x72, 0x20, 0xf7, 0xab, 0x1b, 0xff, 0xa6, 0x48, 0x26, 0x4c, 0x9e,
	0x41, 0xf4, 0xa1, 0x37, 0xf6, 0xe8, 0x40, 0x6d, 0xa5, 0xba, 0x7b, 0x60, 0x07, 0x9b, 0xda, 0x32,
	0x7d, 0xdc, 0xe2, 0x7d, 0x7f, 0x38, 0xdc, 0x3d, 0xf0, 0x12, 0xb6, 0x17, 0x83, 0xb1, 0x6c, 0xe0,
	0x78, 0xfc, 0xae, 0x17, 0x10, 0x9f, 0x59, 0xcb, 0xf8, 0x9e, 0x6c, 0xab, 0x6b, 0x9b, 0x52, 0xcc,
	0x68, 0x7c, 0xfa, 0x47, 0x10, 0x9d, 0x39, 0xbb, 0x27, 0x9b, 0xca, 0x2f, 0xf2, 0xf2, 0xf5, 0xb7,
	0x38, 0x2c, 0xff, 0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x5b, 0x8b, 0x6f, 0x0f, 0x03,
	0x00, 0x00,
}
